#!/bin/sh -e

### BEGIN INIT INFO
# Provides: firstboot
# Required-Start: $all
# Required-Stop:
# Default-Start: S
# Default-Stop:
# X-Start-Before: ssh brickman
# Short-Description: ev3dev first boot tasks
### END INIT INFO

case "$1" in
    start)
        update-rc.d -f firstboot remove

        # expand the root file system
        # Note, this will break if using an initramfs
        parted --script /dev/mmcblk0 unit % resizepart 2 100%
        partprobe
        resize2fs /dev/mmcblk0p2
        ;;
    stop|restart|reload|force-reload|status)
        :
        ;;
    *)
        echo "Usage: /etc/init.d/firstboot start"
        exit 1
        ;;
esac

exit 0
